runner.dialect = scala213

// Built in rules
rules = [
  NoAutoTupling  // Rewrite that inserts explicit tuples for adapted argument lists for compatibility with -Yno-adapted-args
  NoValInForComprehension
  ProcedureSyntax
//  RemoveUnused
  LeakingImplicitClassVal
  ExplicitResultTypes
  // Additional rules for fixing quickfixable warnings
  DisableSyntax,
  OrganizeImports
]

//RemoveUnused {
//  imports = true
//  privates = true
//  locals = false
//  // "locals" is incompatible with `shouldNotCompile`
//  patternvars = true
//  params = true
//}

ExplicitResultTypes {
  rewriteStructuralTypesToNamedSubclass = false
  skipSimpleDefinitions = false

  onlyImplicits = true
}

DisableSyntax {
  noVars = false
  noThrows = false
  noNulls = false
  noReturns = false
  noWhileLoops = false
  noAsInstanceOf = false
  noIsInstanceOf = false
  noXml = false
  noDefaultArgs = false
  noFinalVal = false
  noFinalize = false
  noValPatterns = false
  noUniversalEquality = false
  noUniversalEqualityMessage = ""
  regex = []
}

OrganizeImports {
  coalesceToWildcardImportThreshold = 999 
  removeUnused = true
  expandRelative = true
  groupedImports = Merge
}